dcvc:
    startR: 0.35 #0.35 start range resolution
    deltaR: 0.0004  #0.0004 range resolution decrease value with range increasing
    deltaP: 1.2 # 1.2 pitch resolution (degree)
    deltaA: 1.2 # 1.2 azimuth resolution (degree)
    min_range: 2 # 0.5 minimum range of lidar
    max_range: 80 # 80 maximum range of lidar
    min_cluster_size: 20