travel:
    vert_scan: 16
    horz_scan: 3600
    min_vert_angle: -15.0
    max_vert_angle: 15.0
    downsample: 1
    horz_merge_thres: 0.4
    vert_merge_thres: 2.1
    vert_scan_size: 3
    horz_scan_size: 5
    horz_skip_size: 5
    horz_extension_size: 5
    min_range: 2 # 0.5 minimum range of lidar
    max_range: 80 # 80 maximum range of lidar
    min_cluster_size: 20
    max_cluster_size: 30000
