verbose: false
dataset:
  name: hit_ms
  dataset_root: /media/qzj/QZJ1T/datasets/HIT/dataset
  sensor_dir: "configs/sensors/horizon" # velodyne, ouster, rslidar

  min_range: 2 # 0.5 minimum range of lidar
  max_range: 40 # 80 maximum range of lidar
  min_cluster_size: 20 # 20 minimum cluster size of lidar

front_end: "gem" # gem, fpfh
cluster_mtd: "dcvc" # euc, dcvc, travel
back_end: "pagor" # pagor, ransac, 3dmac
mac_solver: "pmc" # pmc, clipper, pyclipper
tf_solver: "gmm_tls" # teaser, gnc, quatro, svd, gmm_tls
verify_mtd: "voxel" # voxel, pc

association:
  method: "wasserstein" # all, iou, wasserstein
  num_clusters: 20 # maximum number of clusters
  num_planes: 20 # maximum number of planes
  num_lines: 20 # maximum number of lines
  topK: 20 # topk association

vertex:
  type: "ellipse" # gaussian, point_ratio, ellipse, point
  noise_bound_vec: [0.115, 0.352, 0.584, 1.005]
